import numpy as np
import pandas as pd

rnn_same = [['to', 'be', 'able', 'to', 'be', 'a', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>']
,['of', 'the', 'company', "'s", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>']
,['to', 'be', 'able', 'to', 'be', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>']
,['<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', 'to', 'the', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will']
,['to', 'be', 'able', 'to', 'be', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>']
,['of', 'the', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>']
,['of', 'the', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>']
,['of', 'the', 'company', "'s", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>']
,['to', 'be', 'able', 'to', 'be', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>']
,['<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', 'to', 'the', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will']]

rnn_double = [["'s", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', 'to', 'the', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>']
,['of', 'the', 'company', "'s", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will']
,['<eos>', 'the', 'company', "'s", '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['to', 'be', 'sold', 'by', 'the', 'company', "'s", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the']
,['of', 'the', '<unk>', "'s", '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', 'to', 'the', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>']
,['of', 'the', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['<eos>', 'but', 'the', 'company', "'s", '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>']
,['<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', 'to', 'the', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>']
,["'s", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', 'to', '<unk>', 'the', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'is', "n't", '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a', '<unk>', '<unk>', '<eos>', 'the', 'company', 'said', 'it', 'will', 'be', 'a']]


gru_same = [['N', 'N', '<eos>', 'the', 'key', 'rate', 'of', 'the', 'bills', 'was', 'quoted', 'at', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'was', 'N', 'N', 'to', 'N', 'N', 'N', 'to', 'yield']
,['nov.', 'N', 'N', '<eos>', 'the', 'company', 'said', 'it', 'will', 'redeem', '$', 'N', 'million', 'of', 'assets', 'and', 'N', 'N', 'of', 'the', 'N', 'N', 'convertible', 'subordinated', 'debentures', 'due', 'nov.', 'N', 'N', '<eos>', 'the', 'notes', 'are', 'rated', 'triple-a']
,['the', 'N', 'N', 'stake', 'in', 'the', 'u.s.', 'and', 'the', 'N', 'N', 'stake', 'in', 'the', 'u.s.', '<eos>', 'the', 'N', 'N', 'N', 'rate', 'was', 'due', 'to', 'N', 'N', 'in', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due']
,['to', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['to', 'N', 'N', 'of', 'the', 'N', 'N', 'of', 'the', 'company', "'s", 'shares', 'outstanding', '<eos>', 'the', 'company', 'said', 'it', 'will', 'sell', 'N', 'million', 'shares', 'of', 'N', 'N', 'of', 'the', 'shares', 'outstanding', '<eos>', 'the', 'company', 'said', 'it']
,['of', 'the', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>']
,['and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['funds', '<eos>', 'the', 'new', 'york', 'stock', 'exchange', "'s", '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['macy', '&', 'co.', 'said', 'it', 'agreed', 'to', 'acquire', 'its', 'N', 'N', 'stake', 'in', 'the', 'u.s.', 'and', '<unk>', 'concern', '<eos>', 'the', 'company', 'said', 'it', 'will', 'sell', 'its', 'N', 'N', 'stake', 'in', 'the', 'u.s.', 'and', 'N', 'N']
,['and', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']]

gru_double = [['and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the']
,['sachs', '&', 'co.', 'and', 'salomon', 'brothers', 'inc', '<eos>', 'the', 'move', 'is', 'a', '<unk>', 'of', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and']
,['<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and']
,['at', 'par', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N']
,['candidates', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['<unk>', 'is', 'a', '<unk>', 'of', 'the', '<unk>', 'of', 'the', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['requirements', 'for', 'the', 'first', 'time', 'to', 'be', 'paid', 'for', 'the', 'first', 'time', '<eos>', 'the', '<unk>', 'bill', 'is', 'a', '<unk>', 'of', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,["n't", 'be', 'able', 'to', 'pay', 'the', 'debt', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'identify', 'the', 'offer', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'will', 'sell', 'its', 'stake', 'in', 'navigation', 'mixte', 'to']
,['the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
,['firms', 'are', '<unk>', '<eos>', 'the', 'new', 'york', 'stock', 'exchange', "'s", 'new', 'york', 'stock', 'exchange', 'composite', 'trading', 'was', 'down', 'N', 'cents', 'a', 'share', '<eos>', 'the', 'nasdaq', 'composite', 'index', 'rose', 'N', 'to', 'N', '<eos>', 'the', 'nasdaq', 'composite', 'index', 'rose', 'N', 'to', 'N', '<eos>', 'the', 'nasdaq', 'composite', 'index', 'rose', 'N', 'to', 'N', '<eos>', 'the', 'nasdaq', 'composite', 'index', 'rose', 'N', 'to', 'N', '<eos>', 'the', 'nasdaq', 'composite', 'index', 'rose', 'N', 'to', 'N', '<eos>', 'the', 'nasdaq']]

# df = pd.DataFrame(np.array(gru_double).T)
#
# # with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
# #     print(df)
#
# result = df.to_string(index=False, header=False)
# print(result)

b1 = ['nov.', 'N', 'N', '<eos>', 'the', 'company', 'said', 'it', 'will', 'redeem', '$', 'N', 'million', 'of', 'assets', 'and', 'N', 'N', 'of', 'the', 'N', 'N', 'convertible', 'subordinated', 'debentures', 'due', 'nov.', 'N', 'N', '<eos>', 'the', 'notes', 'are', 'rated', 'triple-a']
b2 = ['N', 'N', '<eos>', 'the', 'key', 'rate', 'of', 'the', 'bills', 'was', 'quoted', 'at', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'was', 'N', 'N', 'to', 'N', 'N', 'N', 'to', 'yield']
b3 = ['macy', '&', 'co.', 'said', 'it', 'agreed', 'to', 'acquire', 'its', 'N', 'N', 'stake', 'in', 'the', 'u.s.', 'and', '<unk>', 'concern', '<eos>', 'the', 'company', 'said', 'it', 'will', 'sell', 'its', 'N', 'N', 'stake', 'in', 'the', 'u.s.', 'and', 'N', 'N']

i1 = ['sachs', '&', 'co.', 'and', 'salomon', 'brothers', 'inc', '<eos>', 'the', 'move', 'is', 'a', '<unk>', 'of', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', 'of', 'the', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', 'of', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and']
i2 = ['at', 'par', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N', 'to', 'yield', 'N', 'N', '<eos>', 'the', 'N', 'N', 'N', 'notes', 'due', 'N', 'fell', 'N', 'to', 'N', 'N']
i3 = ["n't", 'be', 'able', 'to', 'pay', 'the', 'debt', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'identify', 'the', 'offer', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'would', "n't", 'elaborate', '<eos>', 'the', 'company', 'said', 'it', 'will', 'sell', 'its', 'stake', 'in', 'navigation', 'mixte', 'to']

w1 = ['and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', 'and', '<unk>', '<unk>', '<eos>', 'the']
w2 = ['of', 'the', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>']
w3 = ['<eos>', 'but', 'the', 'company', "'s", '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<eos>', 'the', '<unk>', '<unk>', '<unk>', '<unk>']

print(" ".join(b3).replace("<", "$<$").replace(">", "$>$"))